name: Postprocessing

on:
  workflow_call:

jobs:
  postprocessing:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0

    - name: Download AutoHotkey v2 and run postproc.ahk
      run: |
        try {
          $source = "https://www.autohotkey.com/download/ahk-v2.zip"
          $dest = "ahk-v2.zip"
          echo "Downloading $source ..."
          Invoke-WebRequest -Uri $source -OutFile $dest
          echo "Extracting files from $dest ..."
          Expand-Archive -Path $dest
          $path = "ahk-v2/AutoHotkey32.exe"
        }
        catch {
          echo "Download failed. Trying choco ..."
          choco install autohotkey.portable --pre --x86
          $path = "AutoHotkey.exe"
        }
        echo "Running postproc.ahk ..."
        Start-Process -FilePath $path -ArgumentList "/ErrorStdOut `"postproc/postproc.ahk`"" -NoNewWindow -Wait

    - name: Commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add target\docs\static\source\data_search.js
        git commit -a --amend --no-edit
        git push --force-with-lease
